### ISSUE TITLE
Tag that shows that someone retweeted a post on my timeline keeps disappearing

### ISSUE THREAD

**Issue by jbraga2002** [Bl4Cc4t/GoodTwitter2#320] opened 2021-07-29 21:37 UTC
I keep having posts from people I don't follow appear on my timeline and wonder "how did this get on my timeline?"
![image](https://user-images.githubusercontent.com/86741028/127567967-8c8577f0-33d4-48a1-affb-cd560552d334.png)

I'd go and open the post and suddenly I see the "(User) retweeted."
![image](https://user-images.githubusercontent.com/86741028/127568102-9cd02dbd-3f42-4183-9e0a-156686bcbdcf.png)

So when I return to my home timeline again, the "retweeted by" tag appears on the tweet as it should, but only for a split second before it disappears again and looks like my first screenshot.
![image](https://user-images.githubusercontent.com/86741028/127568367-d9508bf1-df5f-40ab-8e4d-6dc098ce9a4e.png)

My timeline is always like the first image, where the "retweet by" tag is missing, but only appears after opening a post and returning to my home timeline (and then disappearing again after a second)

**Your configuration**
 - Latest Firefox (90.0.2) 64-bit
 - Tampermonkey v4.13.6136

**Comment by Bl4Cc4t** [comment] 2021-07-29 22:33
probably related to/dupe of #315.

See also #321, since I only mentioned it at some random issues so far.

**Comment by jbraga2002** [comment] 2021-07-30 00:08
Ah my apologies!! Please take your time, wishing the best of luck for you!

**Comment by Bl4Cc4t** [comment] 2021-07-31 18:58
No need to apologize, I'm grateful for any reports I receive

And thanks :)

**Closed** 2021-08-13 17:11 UTC
Labels: bug
