### ISSUE TITLE
Legacy Navbar and Lefthand frames not showing up

### ISSUE THREAD

**Issue by GroundThing** [Bl4Cc4t/GoodTwitter2#172] opened 2020-07-25 02:28 UTC
Recently the Navbar and lefthand frames haven't been showing up when using this. Tried reloading the userscript, but it hasn't fixed it. I saw a previous post about a different layout issue which was fixed in the dev version, but going to the dev branch and loading the userscript from there didn't seem to fix it, so it seems this bug still exists.

![GoodTwitterBug](https://user-images.githubusercontent.com/68763301/88446931-1bcb9180-cdfc-11ea-82bd-125e070f8e08.PNG)

**Comment by Bl4Cc4t** [comment] 2020-07-25 11:41
> but going to the dev branch and loading the userscript from there didn't seem to fix it, so it seems this bug still exists.

This is not a valid reason to open an issue that already exists. I have no idea how you installed the dev version in the first place.

Just be a bit more patient in the future and wait until it gets released for everybody.

Closing this as dupe of #169.

**Closed by Bl4Cc4t** 2020-07-25 11:41 UTC
Labels: bug
