### ISSUE TITLE
Profile Biography bug

### ISSUE THREAD

**Issue by anxiousluku** [Bl4Cc4t/GoodTwitter2#310] opened 2021-06-08 11:28 UTC
**Please check the following before you continue**
- [X] Bug happens with the newest version of GT2 (see the [changelog](https://github.com/Bl4Cc4t/GoodTwitter2/blob/master/doc/changelog.md))
- [x] Checked [FAQ](https://github.com/Bl4Cc4t/GoodTwitter2#faq)
- [x] Checked if the issue has not been reported before

**Describe the bug**
(A clear and concise description of what the bug is.
(What sites does it affect?

Viewing a profile after viewing a previous one before sometimes carries the display name, username, biography (description, birthdate, account creation, links, etc.) and mutual follows over to the second and further profiles.

**Screenshots**
(For display issues, adding screenshots or even videos of your screen is recommended.

1) Viewing a profile (non-yours) for the first time in the session:
![11](https://user-images.githubusercontent.com/76812781/121173473-272f7c00-c859-11eb-8603-8b07e6f13334.png)

2) Viewing a different profile in the same session:
![22](https://user-images.githubusercontent.com/76812781/121173566-40382d00-c859-11eb-802e-22f978df2af1.png)

3) Viewing the same profile as in 2) but on a different session:
![image](https://user-images.githubusercontent.com/76812781/121177495-bd65a100-c85d-11eb-856c-6b3ebfa4ba0b.png)

This happens in formations:
- Account verified -> Account not verified 
- Account verified -> Account verified

- Account not verified -> Account not verified
- Account not verified -> Account verified

- Self -> Different account not verified

**Your configuration**
 - Browser: Microsoft Edge Version 91.0.864.41 (Official build) (64-bit)
 - Userscript Manager: Tampermonkey by Jan Biniok v4.13 (downloaded from the Chrome Web Store)

**Comment by Bl4Cc4t** [comment] 2021-06-08 22:37
Dupe of #232, closing this one.
I really need to fix this, it is so annoying to see.
At least it doesn't happen as often as it used to.

**Closed by Bl4Cc4t** 2021-06-08 22:37 UTC
Labels: bug, duplicate
