### ISSUE TITLE
Mobile browser support?

### ISSUE THREAD

**Issue by GreenDotBlue99** [Bl4Cc4t/GoodTwitter2#447] opened 2022-07-15 02:50 UTC
Code only had this:
// @match         https://twitter.com/*

Should it also have:
// @match         https://*.twitter.com/*
Or
// @match         https://mobile.twitter.com/*

?

**Comment by Bl4Cc4t** [comment] 2022-07-18 00:04
dupe of #104, fixed in #441

**Closed by Bl4Cc4t** 2022-07-18 00:04 UTC
