### ISSUE TITLE
'What's Happening' is back on the right side

### ISSUE THREAD

**Issue by NoThanksPal** [Bl4Cc4t/GoodTwitter2#125] opened 2020-06-18 15:16 UTC

**Comment by NoThanksPal** [comment] 2020-06-18 15:20
Since version 0.0.20, the What's Happening (Trends) has gone back to the right side.

Chrome Version 83.0.4103.106 (Official Build) (64-bit)
![goodtwitter](https://user-images.githubusercontent.com/66384542/85039402-b1b53200-b155-11ea-815c-4ec47a694bb4.png)

**Comment by Bl4Cc4t** [comment] 2020-06-20 09:20
dupe of #87

**Closed by Bl4Cc4t** 2020-06-20 09:20 UTC
Labels: bug
