### ISSUE TITLE
Wrong user information

### ISSUE THREAD

**Issue by CreepasCraft** [Bl4Cc4t/GoodTwitter2#300] opened 2021-05-26 18:41 UTC
**Description**
When viewing someone's profile going back and clicking on another profile it will mix up the information of the first one that was viewed with the pfp of the second

**Screenshots**
What it shows: ![image](https://user-images.githubusercontent.com/39415973/119714076-b6ed2780-be62-11eb-8289-18628aec86f3.png)
After refreshing the page: ![image](https://user-images.githubusercontent.com/39415973/119714127-c8363400-be62-11eb-91e3-26787a5cfdc6.png)

 - Browser Chromium Edge (Also happened back when I was on Opera)
 - TamperMonkey 4.13.6138

**Comment by Bl4Cc4t** [comment] 2021-05-26 18:46
I still do not know how this happens and how to prevent it. I'll try to come up with a fix for the next version.

This is a duplicate of #232, so I'll close this one (you can subscribe to that issue if you want)

**Closed by Bl4Cc4t** 2021-05-26 18:46 UTC
Labels: bug, duplicate

**Comment by CreepasCraft** [comment] 2021-05-26 19:17
My bad, thanks
