### ISSUE TITLE
Clicking on user icon (top right) opens the wrong menu in the wrong place

### ISSUE THREAD

**Issue by frozenpandaman** [Bl4Cc4t/GoodTwitter2#581] opened 2024-02-22 15:16 UTC
Instead of the normal menu dropdown on the right side of the screen (links to random stuff, with 'settings' and 'sign out' at the bottom), clicking on your user icon now shows this in the top left:

<img width="313" alt="image" src="https://github.com/Bl4Cc4t/GoodTwitter2/assets/7245874/5cbb107d-7c01-4b83-9dea-e8d79bb34e1f">

('Bookmarks' may or may not be displayed depending on the height of the window.)

Anyone have a fix?

**Comment by Bl4Cc4t** [comment] 2024-02-22 18:53
Sorry for the long absence (again)
fixed it in 54fcea112647156d8ca6741dcb0f3d6f14739bd3
duplicate of #577
see https://github.com/Bl4Cc4t/GoodTwitter2/releases/tag/v1.0.0-beta.2 for latest beta

**Closed by Bl4Cc4t** 2024-02-22 18:53 UTC
Labels: bug
