### ISSUE TITLE
Tab title - the number of unread tweets

### ISSUE THREAD

**Issue by NoThanksPal** [Bl4Cc4t/GoodTwitter2#61] opened 2020-06-03 18:36 UTC
Prior to using GT2, the tab in Chrome I had Twitter open on would indicate if I had any new tweets, similar to this image.  Now it is just saying 'Latest Tweets/Twitter' at all times.
[How it used to look](http://i.imgur.com/LXruIg8.png)

**Comment by Bl4Cc4t** [comment] 2020-06-03 22:46
duplicate of #14

**Closed by Bl4Cc4t** 2020-06-03 22:46 UTC
Labels: duplicate
