### ISSUE TITLE
Navbar and Profile gone after update

### ISSUE THREAD

**Issue by DNSDies** [Bl4Cc4t/GoodTwitter2#135] opened 2020-06-20 21:39 UTC
**Please check the following before you continue**
- [x] Checked [FAQ](https://github.com/Bl4Cc4t/GoodTwitter2#faq)
- [X] Checked if the issue has not been reported before

**Describe the bug**
Twitter main page, and any other pages, I can't see the navbar and the profile section on the left is missing. This happened right after an auto-update of the script.

**Screenshots**
https://imgur.com/a/fSMgFi6

**Your configuation**
 - Waterfox 2020.06 64bit
 - Tampermonkey v4.11.6114

**Comment by MattPD** [comment] 2020-06-20 23:50
Can confirm and reproduce on Firefox 77.0.1 (64-bit) with Violentmonkey 2.12.7.

In case you're bisecting this, the version in this commit made these re-appear for me (however, text contents "Tweets", "Following", "Followers", and "Tweet" have been replaced by "undefined"):
https://github.com/Bl4Cc4t/GoodTwitter2/blob/fc5ce1557d55122d757b50d142d83b7cc0038576/twitter.gt2eb.user.js

**Comment by DNSDies** [comment] 2020-06-21 00:40
I can confirm that the script version MattPD posted does fix things, for the most part. Only problem are the undefined values.

**Comment by seanking2919** [comment] 2020-06-21 04:27
Having a similar issue here on Waterfox post-update: 
![image](https://user-images.githubusercontent.com/31253278/85216706-34e8aa80-b345-11ea-98ce-f7daf6217438.png)

**Comment by Bl4Cc4t** [comment] 2020-06-21 13:39
Aaaargh, Firefox back at it again
The issue comes from an XMLHttpRequest and I have no idea why it is not coming through, since I don’t even get a response nor an error code

**Comment by FortunaDraken** [comment] 2020-06-21 15:26
I'm having the same issues on Chrome, using ViolentMonkey. Figured I'd mention it since the reports have been Firefox related so far.

**Comment by spodermenpls** [comment] 2020-06-21 18:40
@Bl4Cc4t It's still messed up with 0.22.3 on my end.

**Comment by Bl4Cc4t** [comment] 2020-06-21 19:41
@spodermenpls ...and you are using what combination of software?

**Comment by spodermenpls** [comment] 2020-06-21 20:12
@Bl4Cc4t The same as MattPD; Violentmonkey and FF 77.0.1. It still looks the same as in seanking's screenshot, unfortunately. Is there some log or so that might be useful for you?

**Comment by Bl4Cc4t** [comment] 2020-06-21 21:32
@spodermenpls I use the same combination and it works. what is the error message you get in the console?

**Comment by spodermenpls** [comment] 2020-06-21 22:11
@Bl4Cc4t I've got this:

```
TypeError: "GM_getValue(...).match(...) is null"
    locStr moz-extension://168f9ff1-f25f-4cec-895d-109e95e90168/GoodTwitter 2 - Electric Boogaloo.user.js#2:568
    getDashboardProfile moz-extension://168f9ff1-f25f-4cec-895d-109e95e90168/GoodTwitter 2 - Electric Boogaloo.user.js#2:950
    urlChange moz-extension://168f9ff1-f25f-4cec-895d-109e95e90168/GoodTwitter 2 - Electric Boogaloo.user.js#2:1747
    <anonymous> moz-extension://168f9ff1-f25f-4cec-895d-109e95e90168/GoodTwitter 2 - Electric Boogaloo.user.js#2:1828
    <anonymous> moz-extension://168f9ff1-f25f-4cec-895d-109e95e90168/GoodTwitter 2 - Electric Boogaloo.user.js#2:1853
    <anonymous> moz-extension://168f9ff1-f25f-4cec-895d-109e95e90168/GoodTwitter 2 - Electric Boogaloo.user.js#2:1855
    <anonymous> moz-extension://168f9ff1-f25f-4cec-895d-109e95e90168/GoodTwitter 2 - Electric Boogaloo.user.js#2:1855
    <anonymous> moz-extension://168f9ff1-f25f-4cec-895d-109e95e90168/GoodTwitter 2 - Electric Boogaloo.user.js#2:1855
GoodTwitter 2 - Electric Boogaloo.user.js:1855:27
    <anonym> moz-extension://168f9ff1-f25f-4cec-895d-109e95e90168/GoodTwitter 2 - Electric Boogaloo.user.js#2:1855
    <anonym> moz-extension://168f9ff1-f25f-4cec-895d-109e95e90168/GoodTwitter 2 - Electric Boogaloo.user.js#2:1855
```

**Comment by Bl4Cc4t** [comment] 2020-06-22 09:29
@spodermenpls okay, this is interesting. 
please head over to the VM dashboard and click on edit:
![image](https://user-images.githubusercontent.com/6740726/85271631-58ae0c80-b47b-11ea-87dd-644b9bc65440.png)
Next, go to the values section and please tell me, what the value for `i18n_internal_rweb` is (if it exists).

**Comment by spodermenpls** [comment] 2020-06-22 13:56
@Bl4Cc4t This is what gets displayed there:

`"\n<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\"\n \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">\n<html>\n  <head>\n    <title>503 backend read error</title>\n  </head>\n  <body>\n    <h1>Error 503 backend read error</h1>\n    <p>backend read error</p>\n    <h3>Guru Mediation:</h3>\n    <p>Details: cache-fty21332-FTY 1592667495 563613402</p>\n    <hr>\n    <p>Varnish cache server</p>\n  </body>\n</html>\n"`

**Comment by Bl4Cc4t** [comment] 2020-06-22 16:57
hm, does it work again if you delete the value?

**Comment by spodermenpls** [comment] 2020-06-22 17:16
Yes, that did the trick, it fell back to the English locale now and gets displayed properly again. The "Trends" module configs still only work while logged-out, though, it only displays the line "Trends" on the right sidebar, not being moved to the left and displaying all 10 trends, like it does while logged-out. Is this a general problem, or again just on my end?

**Comment by Bl4Cc4t** [comment] 2020-06-22 17:20
Seems like there are two different issues, one is related to VM and the other to Firefox 68 (Waterfox).

For VM, I forgot to add the `method` parameter in the query. TM assumes GET when omitting it, while VM does not do that. Very dumb error on my part.

When using TM with Waterfox, I get `resource xy was blocked because content blocking is enabled` warnings for the files I am trying to request.
I am not sure if I can do anything about that, sadly.

@spodermenpls please open a new issue for that with pictures, this sounds like it is not related to this issue

**Comment by MattPD** [comment] 2020-06-24 09:49
I can confirm that removing the 503 error text in `i18n_internal_rweb` fixed the issue for me, too!

**Comment by seanking2919** [comment] 2020-06-24 22:46
Yep, it's all fixed on my end after this update, too.

**Comment by FortunaDraken** [comment] 2020-06-25 13:27
@Bl4Cc4t I don't know if it's the same reason or not, but my nav bar and left side bar are gone after my Twitter refreshed automatically (I assume that's when GoodTwitter updated) a few hours ago. I'm using ViolentMonkey and Google Chrome.

This error is showing in the console
> Uncaught TypeError: Cannot read property '1' of null
    at locStr (chrome-extension://jinjaccalgkegednnccohejagnlnfdag/GoodTwitter%202%20-%20Electric%20Boogaloo.user.js#3:568)
    at getDashboardProfile (chrome-extension://jinjaccalgkegednnccohejagnlnfdag/GoodTwitter%202%20-%20Electric%20Boogaloo.user.js#3:950)
    at urlChange (chrome-extension://jinjaccalgkegednnccohejagnlnfdag/GoodTwitter%202%20-%20Electric%20Boogaloo.user.js#3:1747)
    at chrome-extension://jinjaccalgkegednnccohejagnlnfdag/GoodTwitter%202%20-%20Electric%20Boogaloo.user.js#3:1828
    at chrome-extension://jinjaccalgkegednnccohejagnlnfdag/GoodTwitter%202%20-%20Electric%20Boogaloo.user.js#3:1853
    at chrome-extension://jinjaccalgkegednnccohejagnlnfdag/GoodTwitter%202%20-%20Electric%20Boogaloo.user.js#3:1855
    at Proxy.<anonymous> (chrome-extension://jinjaccalgkegednnccohejagnlnfdag/GoodTwitter%202%20-%20Electric%20Boogaloo.user.js#3:1855)
    at chrome-extension://jinjaccalgkegednnccohejagnlnfdag/GoodTwitter%202%20-%20Electric%20Boogaloo.user.js#3:1855
    at Object.post (chrome-extension://jinjaccalgkegednnccohejagnlnfdag/sandbox/injected-web.js:1)
    at y (chrome-extension://jinjaccalgkegednnccohejagnlnfdag/sandbox/injected-web.js:1)

**Comment by KudaKeil** [comment] 2020-06-29 02:30
Happening over here for me again. Latest Firefox, latest script update, ViolentMonkey.

https://i.imgur.com/GL72AaK.png

**Comment by Bl4Cc4t** [comment] 2020-07-23 19:18
This issue could potentially be fixed with the next update.
I removed the `i18n_internal_rweb` stuff completely, so no request should be made.

**Comment by Bl4Cc4t** [comment] 2020-07-25 20:44
Please feel free to open a new issue if something breaks again

**Closed by Bl4Cc4t** 2020-07-25 20:44 UTC
Labels: bug, fixed in dev
