### ISSUE TITLE
"Left sidebar trends" toggle not working

### ISSUE THREAD

**Issue by shootlazer** [Bl4Cc4t/GoodTwitter2#29] opened 2020-06-01 23:47 UTC
The toggle doesn't seem to work on any browser since it was added, even tried several language settings but it doesn't do anything. Neither does enabling/disabling/clearing cache.

**Comment by loldudester** [comment] 2020-06-02 01:21
Same issue here.

**Comment by Bl4Cc4t** [comment] 2020-06-02 11:03
Please update to the latest version and try again. 
I’m fixing things left and right and don’t really know what exact version you were using...

**Comment by shootlazer** [comment] 2020-06-02 18:18
> Cannot reproduce on the latest version.
> Please update to the latest version and try again.
> I’m fixing things left and right and don’t really know what exact version you were using...

Tried on latest version. Used different PCs, different accounts and even different browsers and language, but sadly doesn't work

**Comment by cszabla** [comment] 2020-06-02 20:08
I have been able to get the profile info on the left side ONLY when zoomed to 90% or less. Zooming to 100% or more moves it to the right. Trends just don't move to the left at all.

**Comment by shootlazer** [comment] 2020-06-02 21:46
> I have been able to get the profile info on the left side ONLY when zoomed to 90% or less. Zooming to 100% or more moves it to the right. Trends just don't move to the left at all.

Profile info works fine @ 1080p 100%.
For me it only moves to the right when zooming it to 175%
But the trends tab doesn't move to the left, no matter how I zoom.

**Comment by go2tom42** [comment] 2020-06-03 03:17
Does not work for me in Chrome or Firefox.

**Comment by NoThanksPal** [comment] 2020-06-04 13:52
I also have this issue. 

GoodTwitter2 v0.0.18
Windows 10 Home 1809
Intel(R) Core i9-9900K
Chrome Version 83.0.4103.97 (Official Build) (64-bit)

**Comment by Bl4Cc4t** [comment] 2020-06-05 17:24
Can someone please attach a screenshot? I am still not able to reproduce this.

**Comment by NoThanksPal** [comment] 2020-06-05 17:33
![trending on right](https://user-images.githubusercontent.com/66384542/83906208-2c7f5580-a731-11ea-86bb-d4f9ea1706d8.png)

**Comment by Bl4Cc4t** [comment] 2020-06-05 17:54
perfect, thank you. I think I found the error.

**Comment by go2tom42** [comment] 2020-06-07 20:23
The issue was temporarily fixed for me with 0.0.20, but 12 hours later it no longer works on both Firefox & Chrome

**Comment by Bl4Cc4t** [comment] 2020-06-07 20:56
please send a screenshot of what you are seeing

**Comment by go2tom42** [comment] 2020-06-07 21:01
NP
![Home_Twitter_-_2020-06-07_17 00 07](https://user-images.githubusercontent.com/12462792/83980050-86724d80-a8e0-11ea-8606-6205d50050c7.jpg)

**Comment by Bl4Cc4t** [comment] 2020-06-08 11:01
My main problem with fixing that is that I do not get the “What’s happening” trends at all.
I only get “Trends for you”...

**Comment by go2tom42** [comment] 2020-06-08 16:36
I've flipped every setting in twitter and can not get anything but “What’s happening”

**Comment by Aridow** [comment] 2020-06-12 22:44
It seems since the last update, the "left sidebar trends" toggle doesn't work every time (with Firefox and Chrome), anyone have this issue ?

**Comment by Bl4Cc4t** [comment] 2020-06-13 00:15
yes, this has already been reported. will be fixed tomorrow.

**Comment by Bl4Cc4t** [comment] 2020-06-13 10:16
Okay, gonna close this again in favor of #87

**Closed by Bl4Cc4t** 2020-06-13 10:16 UTC
