### ISSUE TITLE
auto suppression of "Latest Tweets show up as they happen" pop up

### ISSUE THREAD

**Issue by yarrmateys** [Bl4Cc4t/GoodTwitter2#197] opened 2020-09-13 03:23 UTC
if you use the option to display new tweets first, the page will always automatically force this nag screen trying to goad you into switching back to top tweets, even going as far as claiming it's wrong and "top tweets" is the true home page. as long as it's visible it corrupts access to the options, profile etc. and it always pops up on every refresh, and just simply hiding it through css also hides access to half of the profile options. could it be suppressed so that the page automatically thinks it was dismissed as soon as it's loaded?

**Comment by Bl4Cc4t** [comment] 2020-09-13 10:44
dupe of #194

**Closed by Bl4Cc4t** 2020-09-13 10:44 UTC
Labels: enhancement
