### ISSUE TITLE
Long nicknames

### ISSUE THREAD

**Issue by igorterleg** [Bl4Cc4t/GoodTwitter2#72] opened 2020-06-04 11:47 UTC
Long nicknames are displayed over follower/following count etc:

![image](https://user-images.githubusercontent.com/21354643/83753022-d2678d00-a669-11ea-9290-88a13296b106.png)

I added this to my user style to make it look like it did on old Twitter, seems to work:

```
.gt2-user {
    text-overflow: ellipsis;
    white-space: nowrap;
}
```

**Comment by Bl4Cc4t** [comment] 2020-06-04 12:33
This has already been fixed in https://github.com/Bl4Cc4t/GoodTwitter2/commit/a945f719d10abcda4c5c6d35260a07d03661e82e
Please update.

**Comment by igorterleg** [comment] 2020-06-04 14:39
Updated, even reinstalled from scratch, it's still wrapping. :(

Chrome 83.0.4103.61
TM 4.10

**Comment by Bl4Cc4t** [comment] 2020-06-04 17:15
oh, I think I know what the problem is, I forgot the `white-space: nowrap;` you included. 
sorry, I’m getting more and more lost :D

**Closed** 2020-06-06 18:04 UTC
Labels: bug
