### ISSUE TITLE
Notifications not showing

### ISSUE THREAD

**Issue by GOOPREALM5000** [Bl4Cc4t/GoodTwitter2#466] opened 2022-08-26 06:56 UTC
Every time I get a notification with GT2 installed, it doesn't show up on the web app. Notifications show up fine on mobile and my other computer which doesn't have GT2 installed, so I already know this is a GT2 problem rather than a Twitter problem. Notifications do still appear in the browser tab though.
![image](https://user-images.githubusercontent.com/112156499/186841465-9c3723c7-8f0b-4b9f-ac68-aed0ad6ad403.png)

**Comment by Bl4Cc4t** [comment] 2022-08-26 19:11
dupe of #459

**Closed by Bl4Cc4t** 2022-08-26 19:11 UTC
Labels: bug
