### ISSUE TITLE
Wider Profiles

### ISSUE THREAD

**Issue by GitHubNme** [Bl4Cc4t/GoodTwitter2#66] opened 2020-06-03 23:39 UTC
It looks like the new Twitter profiles have three vertical tables. Wider profiles would use up the empty real estate on the left side (what looks like an empty table now with this script in place) and make visiting/viewing profiles much more intuitive and easy on the eye.

**Comment by Bl4Cc4t** [comment] 2020-06-05 18:17
hm, I think this is a dupe of #8 ;)

**Closed** 2020-06-12 13:35 UTC
Labels: enhancement
